name: Check NetApp Version

on:
  schedule:
    - cron: '0 13 * * *'  # Revisa todos los días
  workflow_dispatch:      # Permite botón manual

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - id: run_script
        run: python check_ontap.py

      # Envía el correo avisándote que hay algo nuevo por instalar
      - name: Enviar correo de notificación
        if: steps.run_script.outputs.actualizado == 'true'
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: '¡Alerta NetApp! Nueva versión disponible en la Web: ${{ steps.run_script.outputs.version }}'
          to: ${{ secrets.EMAIL_USERNAME }}
          from: 'NetApp Version Monitor'
          body: |
            Hola,
            
            Se ha detectado que NetApp publicó una nueva versión: ${{ steps.run_script.outputs.version }}.
            
            Tu repositorio sigue marcado con la versión anterior porque no la has instalado. Una vez que la instales en tu infraestructura, recuerda actualizar el archivo 'ultima_version.txt' en GitHub de forma manual.
