name: Check NetApp Version

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # ESTE PASO ES CLAVE: Instala BeautifulSoup y Requests en GitHub
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - id: run_script
        run: python check_ontap.py

      # Paso para guardar la versión de vuelta en el repositorio si cambia
      - name: Guardar nueva versión en el repositorio
        if: steps.run_script.outputs.actualizado == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ultima_version.txt
          git commit -m "chore: actualizar registro a versión ${{ steps.run_script.outputs.version }}"
          git push
